services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: cinema-oracle-db
    environment:
      - ORACLE_PASSWORD=dev123
      - APP_USER=dev
      - APP_USER_PASSWORD=dev123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./sql:/docker-entrypoint-initdb.d  # THÊM DÒNG NÀY ĐỂ KẾT NỐI FILE SQL
volumes:
  oracle_data:
    driver: local